CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identification_type VARCHAR(30) NOT NULL,
  identification_number VARCHAR(50) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  birth_date DATE NOT NULL,
  creation_date TIMESTAMP,
  modification_date TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_type VARCHAR(30) NOT NULL,
  account_number VARCHAR(10) NOT NULL UNIQUE,
  status VARCHAR(30) NOT NULL,
  balance NUMERIC(19,2) NOT NULL DEFAULT 0,
  gmf_exempt BOOLEAN NOT NULL DEFAULT FALSE,
  creation_date TIMESTAMP,
  modification_date TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  client_id BIGINT NOT NULL,
  CONSTRAINT fk_accounts_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_type VARCHAR(30) NOT NULL,
  amount NUMERIC(19,2) NOT NULL,
  date TIMESTAMP NOT NULL,
  origin_account_id BIGINT NOT NULL,
  destination_account_id BIGINT,
  description VARCHAR(500),
  CONSTRAINT fk_tx_origin FOREIGN KEY (origin_account_id) REFERENCES accounts(id),
  CONSTRAINT fk_tx_dest FOREIGN KEY (destination_account_id) REFERENCES accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_client_id ON accounts(client_id);
CREATE INDEX IF NOT EXISTS idx_tx_origin ON transactions(origin_account_id);
CREATE INDEX IF NOT EXISTS idx_tx_dest ON transactions(destination_account_id);
